### ISSUE TITLE
Mi primer issue

### ISSUE THREAD

**Issue by maritzavillela** [craft2es/githubparaperiodistas#10]
Dirección de tu cuenta de usuario en Github: github.com/maritzavillela

Dirección de tu sitio web en Github: maritzavillela.github.io

Cosas no te quedaron claras: Las instrucciones estaban claras y pude seguirlas. Pero, aún me cuesta entender que hacer con el desktop y el propósito de guardar todo allí y hacerle sync. El fork es como un copy-paste para yo poder trabajar en el trabajo de alguien más? Y poder ver todos los cambios?

**Comment by miguelpaz** [comment]
Ok. Hoy tendremos un rato de la clase para repasar estos temas.
