### ISSUE TITLE
Mi primer issue

### ISSUE THREAD

**Issue by jeseniademoyac** [craft2es/githubparaperiodistas#2]
Hola Profe Miguel,

Mi cuenta de usuario es: github.com/jeseniademoyac
Y mi sitio web en GitHub es jeseniademoyac.github.io
Tuve problemas para publicar el issue porque no sabía donde estaba el botón para hacerlo. No sé porqué pero los ojos como que se me pierden entre tantas letras juntas y cosas pa' punchar. 

Lo veo mañana.

**Comment by miguelpaz** [comment]
Perfecto Jesenia. Ahora cierro el issue.
