### ISSUE TITLE
Mi primer issue

### ISSUE THREAD

**Issue by mariamontanez** [craft2es/githubparaperiodistas#3]
github.com/mariamontanez mariamontanez.github.io

Las instrucciones fueron claras entonces no tuve problema en hacer este trabajo.

**Comment by miguelpaz** [comment]
Ok. ¿No tiene dominio personal tipo camilamontanez.com o algo similar?

**Comment by mariamontanez** [comment]
Yo tengo un dominio persona con midphase: maria-camila-montanez.com

**Comment by miguelpaz** [comment]
Ok. Cierro el issue.
