### ISSUE TITLE
Mi primer issue

### ISSUE THREAD

**Issue by estefaniahernandez** [craft2es/githubparaperiodistas#4]
https://github.com/estefaniahernandez
https://estefaniahernandez.github.io/project1/ 

Las instrucciones fueron claras entonces no hubo ningun problema.

**Comment by miguelpaz** [comment]
Gracias Estefanía. También le pedí indicar cuál es su dominio si tiene uno.

**Comment by estefaniahernandez** [comment]
@miguelpaz El domain lo puse como el primero: https://github.com/estefaniahernandez y el segundo fue la pagina web.

**Comment by miguelpaz** [comment]
Me refería a si tienes un dominio tipo estefaniahernandez.com

**Comment by estefaniahernandez** [comment]
Aun no tengo, el unico que tengo es esto: https://hernandezestefania.wordpress.com/

**Comment by miguelpaz** [comment]
Ok. Cierro el issue.
