### ISSUE TITLE
Mi primer issue

### ISSUE THREAD

**Issue by gerardodelvalle** [craft2es/githubparaperiodistas#5]
https://github.com/gerardodelvalle

Creo que entendí todo.

**Comment by miguelpaz** [comment]
Ok. Le falto indicar cuál es su dominio personal (gerardo.com, gdv.gt, etc. ¿cuál es?). Y no hizo fork del repositorio. Le falta eso.

**Comment by gerardodelvalle** [comment]
Sí hice fork del repositorio y mi dominio personal: gdelvalle.com
