### ISSUE TITLE
Mi primer issue

### ISSUE THREAD

**Issue by monicacorderosancho** [craft2es/githubparaperiodistas#6]
https://github.com/monicacorderosancho

Entendido.

**Comment by miguelpaz** [comment]
¿Qué fue lo que le costó más entender de Github y en qué necesita ayuda? Responda como parte de la tarea.

**Comment by monicacorderosancho** [comment]
La guía estaba muy clara. Me costó ubicarme mentalmente en la relación de mi disco duro con la nube.  Voy a usarlo más y será más natural.

**Comment by miguelpaz** [comment]
:+1:
Cierro el issue.
