### ISSUE TITLE
Mi primer issue

### ISSUE THREAD

**Issue by hanaatameez** [craft2es/githubparaperiodistas#9]
github.com/hanaatameez
hanaatameez.github.io
Dominio personal (si se necesita): hanaatameez.com

No entiendo a dónde debo llegar con "hanaatameez.github.io" pero espero que entendí casi todo si llegué a este punto. Voy a revisar las instrucciones en inglés también para que todo quede claro.

**Comment by miguelpaz** [comment]
Ok. Haremos repaso hoy.
